/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoomsRouteImport } from './routes/app.rooms'
import { Route as AppRestaurantRouteImport } from './routes/app.restaurant'
import { Route as AppReservationsRouteImport } from './routes/app.reservations'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPreOrderRouteImport } from './routes/app.pre-order'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppHousekeepingRouteImport } from './routes/app.housekeeping'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppBarRouteImport } from './routes/app.bar'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantRoute = AppRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPreOrderRoute = AppPreOrderRouteImport.update({
  id: '/pre-order',
  path: '/pre-order',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHousekeepingRoute = AppHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppBarRoute = AppBarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-login': typeof StaffLoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bar': typeof AppBarRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/housekeeping': typeof AppHousekeepingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/pre-order': typeof AppPreOrderRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/restaurant': typeof AppRestaurantRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-login': typeof StaffLoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bar': typeof AppBarRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/housekeeping': typeof AppHousekeepingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/pre-order': typeof AppPreOrderRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/restaurant': typeof AppRestaurantRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-login': typeof StaffLoginRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bar': typeof AppBarRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/housekeeping': typeof AppHousekeepingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/pre-order': typeof AppPreOrderRoute
  '/app/reports': typeof AppReportsRoute
  '/app/reservations': typeof AppReservationsRoute
  '/app/restaurant': typeof AppRestaurantRoute
  '/app/rooms': typeof AppRoomsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/staff-login'
    | '/admin/dashboard'
    | '/admin/login'
    | '/app/audit'
    | '/app/bar'
    | '/app/expenses'
    | '/app/housekeeping'
    | '/app/inventory'
    | '/app/messages'
    | '/app/pre-order'
    | '/app/reports'
    | '/app/reservations'
    | '/app/restaurant'
    | '/app/rooms'
    | '/app/settings'
    | '/app/staff'
    | '/app/subscription'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/staff-login'
    | '/admin/dashboard'
    | '/admin/login'
    | '/app/audit'
    | '/app/bar'
    | '/app/expenses'
    | '/app/housekeeping'
    | '/app/inventory'
    | '/app/messages'
    | '/app/pre-order'
    | '/app/reports'
    | '/app/reservations'
    | '/app/restaurant'
    | '/app/rooms'
    | '/app/settings'
    | '/app/staff'
    | '/app/subscription'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/staff-login'
    | '/admin/dashboard'
    | '/admin/login'
    | '/app/audit'
    | '/app/bar'
    | '/app/expenses'
    | '/app/housekeeping'
    | '/app/inventory'
    | '/app/messages'
    | '/app/pre-order'
    | '/app/reports'
    | '/app/reservations'
    | '/app/restaurant'
    | '/app/rooms'
    | '/app/settings'
    | '/app/staff'
    | '/app/subscription'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffLoginRoute: typeof StaffLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rooms': {
      id: '/app/rooms'
      path: '/rooms'
      fullPath: '/app/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/restaurant': {
      id: '/app/restaurant'
      path: '/restaurant'
      fullPath: '/app/restaurant'
      preLoaderRoute: typeof AppRestaurantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reservations': {
      id: '/app/reservations'
      path: '/reservations'
      fullPath: '/app/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pre-order': {
      id: '/app/pre-order'
      path: '/pre-order'
      fullPath: '/app/pre-order'
      preLoaderRoute: typeof AppPreOrderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/housekeeping': {
      id: '/app/housekeeping'
      path: '/housekeeping'
      fullPath: '/app/housekeeping'
      preLoaderRoute: typeof AppHousekeepingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bar': {
      id: '/app/bar'
      path: '/bar'
      fullPath: '/app/bar'
      preLoaderRoute: typeof AppBarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBarRoute: typeof AppBarRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppHousekeepingRoute: typeof AppHousekeepingRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPreOrderRoute: typeof AppPreOrderRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppRestaurantRoute: typeof AppRestaurantRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBarRoute: AppBarRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppHousekeepingRoute: AppHousekeepingRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPreOrderRoute: AppPreOrderRoute,
  AppReportsRoute: AppReportsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppRestaurantRoute: AppRestaurantRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffLoginRoute: StaffLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
